---
- name: Execute Script on Slave
  hosts: slave
  become: yes
  tasks:
    - name: Copy the Bash script to the slave machine
      copy:
        src: script.sh 
        dest: ~/script.sh
      register: script_copy_result

    - name: Execute the Bash script on the slave machine
      command: bash ~/script.sh
      when: script_copy_result.changed 

    # - name: Create a cron job for server uptime check
    #   cron:
    #     name: "Server Uptime Check"
    #     minute: 0
    #     hour: 0
    #     job: "uptime >> /var/www/html/uptime_logs.txt"